function plot_exc_gnd(eff_rate, bounds, gt, prior_param, varargin)

    colors = linspecer(4);
    labels = {...
            '95% conf.', ...
            'Post. prob. dist.', ...
            'Prior dist.', ...
            'MAP'};

    if nargin == 5
        labels{end + 1} = 'Real';
    end

    num_columns = numel(labels);
    line_width = 2;
    figure
    h1 = histogram(eff_rate(1:2:end), ...
        'Normalization', 'pdf', ...
        'FaceAlpha', 1, ...
        'FaceColor', colors(1, :));
    hold on
    area([bounds(1, 1), bounds(1, 3)], [max(h1.Values), max(h1.Values)], ...
        'FaceColor', [0, 0, 0.6], ...
        'FaceAlpha', 0.1, ...
        'EdgeColor', 'none')
    uistack(h1, 'top')
    x = linspace(min(eff_rate), max(eff_rate), 3001);
    plot(x, gampdf(x, prior_param(1), prior_param(2) / prior_param(1)), 'Color', colors(2, :), ...
        'LineWidth', line_width)
    plot([gt, gt], [0, max(h1.Values)], ...
        'Color', colors(3, :), ...
        'LineWidth', line_width)

    if nargin == 5
        plot([varargin{1}, varargin{1}], [0, max(h1.Values)], ...
            'Color', colors(3, :), ...
            'LineWidth', line_width)
    end

    hold off
    xlabel('Effective donor exc. rate (ns)^{-1}')
    ylim([0, max(h1.Values)])
    box off

    lgd = legend(labels, ...
        'NumColumns', num_columns, ...
        'FontSize', 11, ...
        'Location', 'northoutside');
    lgd.Box = 'off';
