function p = prob_ecg(time_eff, rate, variance)
    p = rate / 2 ...
        .* exp(-rate .* (time_eff - rate .* variance / 2)) ...
        .* erfc(-(time_eff - rate .* variance) ./ (sqrt(2 * variance)));
