function [V, dVdPSF] = prob_chan_deriv_spat(exc, FRET, rad, conf, exc_prob, fluor, detn, param)
    Q = 1 ./ (sum(exc_prob, 2) + sum(param.ubknd_prob) + 1);

    esc = esc_eff(FRET, rad(1), fluor, conf(detn.idx));
    prob_donor_emis = rad(1) ./ esc;
    prob_FRET = 1 - prob_donor_emis;

    ipD = detn.idx(detn.idx_donor); % idx_pulse_donor
    ipA = detn.idx(detn.idx_accep); % idx_pulse_accep

    % single particle
    rte = exc .* (exc_prob + 1); % rate times exponential

    q1 = exc_prob(ipD, 1) .* prob_donor_emis(detn.idx_donor) .* param.xtalk_prob(1, 1) ...
        + exc_prob(ipD, 1) .* prob_FRET(detn.idx_donor) .* param.xtalk_prob(2, 1) ...
        + exc_prob(ipD, 2) .* param.xtalk_prob(2, 1) ...
        + param.ubknd_prob(1);
    q2 = exc_prob(ipA, 1) .* prob_donor_emis(detn.idx_accep) .* param.xtalk_prob(1, 2) ...
        + exc_prob(ipA, 1) .* prob_FRET(detn.idx_accep) .* param.xtalk_prob(2, 2) ...
        + exc_prob(ipA, 2) .* param.xtalk_prob(2, 2) ...
        + param.ubknd_prob(2);

    V = -sum(log(Q)) - sum(log(q1)) - sum(log(q2));

    dVdPSF = -Q .* sum(rte, 2);
    dq1dPSF = rte(detn.idx_donor, 1) .* (...
        prob_donor_emis(detn.idx_donor) .* param.xtalk_prob(1, 1) ...
        + prob_FRET(detn.idx_donor) .* param.xtalk_prob(2, 1)) ...
        + rte(detn.idx_donor, 2) .* param.xtalk_prob(2, 1);
    dq2dPSF = rte(detn.idx_accep, 1) .* (...
        prob_donor_emis(detn.idx_accep) .* param.xtalk_prob(1, 2) ...
        + prob_FRET(detn.idx_accep) .* param.xtalk_prob(2, 2)) ...
        + rte(detn.idx_accep, 2) .* param.xtalk_prob(2, 2);

    dVdPSF(ipD) = dVdPSF(ipD) + dq1dPSF ./ q1;
    dVdPSF(ipA) = dVdPSF(ipA) + dq2dPSF ./ q2;
    dVdPSF = -param.pulse_width * dVdPSF;
