function prob = prob_obs(detn, traj, phys, param)
    prob_no_emis = 1 ./ (sum(traj.exc_prob, 2) + sum(param.ubknd_prob) + 1);

    esc = esc_eff(traj.conf(detn.idx), traj.fluor, phys.rad(1), phys.FRET);
    emr = esc - phys.rad(2);
    prob_donor_emis = phys.rad(1) ./ esc;
    prob_FRET = 1 - prob_donor_emis;

    ipD = detn.idx(detn.idx_donor); % idx_pulse_donor
    ipA = detn.idx(detn.idx_accep); % idx_pulse_accep

    ecg_esc_prob = prob_ecg(detn.time_eff, esc, param.irf_var);

    prob = ones(size(traj.conf, 1), 1, 'double');
    prob(ipD) ...
        = sum(traj.exc_prob(ipD, 1:2:end) .* prob_donor_emis(detn.idx_donor) .* param.xtalk_prob(1, 1) ...
        .* ecg_esc_prob(detn.idx_donor), 2) ...
        + sum(traj.exc_prob(ipD, 1:2:end) .* prob_FRET(detn.idx_donor) .* param.xtalk_prob(2, 1) ./ emr(detn.idx_donor) ...
        .* (esc(detn.idx_donor) .* detn.ecg_A_prob(detn.idx_donor) - rad(2) .* ecg_esc_prob(detn.idx_donor)), 2) ...
        + sum(traj.exc_prob(ipD, 2:2:end) .* param.xtalk_prob(2, 1), 2) .* detn.ecg_A_prob(detn.idx_donor) ...
        + param.ubknd_prob(1) .* detn.ucg_prob(detn.idx_donor);
    prob(ipA) ...
        = sum(traj.exc_prob(ipA, 1:2:end) .* prob_donor_emis(detn.idx_accep) .* param.xtalk_prob(1, 2) ...
        .* ecg_esc_prob(detn.idx_accep), 2) ...
        + sum(traj.exc_prob(ipA, 1:2:end) .* prob_FRET(detn.idx_accep) .* param.xtalk_prob(2, 2) ./ emr(detn.idx_accep) ...
        .* (esc(detn.idx_accep) .* detn.ecg_A_prob(detn.idx_accep) - rad(2) .* ecg_esc_prob(detn.idx_accep)), 2) ...
        + sum(traj.exc_prob(ipA, 2:2:end) .* param.xtalk_prob(2, 2), 2) .* detn.ecg_A_prob(detn.idx_accep) ...
        + param.ubknd_prob(2) .* detn.ucg_prob(detn.idx_accep);

    prob = prob{idx_roi} .* prob_no_emis;
